# Generated by Django 3.1.14 on 2022-12-30 09:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^(0|\\+98)?9[\\d]{9}$', "Phone number must be entered in the format: '+989123456789'. Up to 12 digits allowed.")], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, default='', max_length=60, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('picture', models.ImageField(default='default.png', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, to='products.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=25)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('street', models.CharField(max_length=25)),
                ('alley', models.CharField(blank=True, max_length=25, null=True)),
                ('postal_code', models.CharField(max_length=13)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
