# Generated by Django 4.1.4 on 2022-12-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
